name: Deploy Lambda

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./Lambda/src

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./Lambda/src
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    # - name: Restore dependencies
    #   run: dotnet restore Services.sln
    # - name: Build
    #   run: dotnet build --no-restore Lambda.csproj
    - name: Deploy to Lambda
      working-directory: ./Lambda/src
      run: dotnet lambda deploy-function Lambda_Function --function-role lambda_role